# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='total_streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='stream_type',
            field=models.CharField(choices=[('all', 'All'), ('live', 'Live'), ('vod', 'VOD')], default='all', max_length=10),
        ),
    ]
