# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_viewing_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='domain',
            field=models.CharField(blank=True, choices=[('etvnet', 'Etvnet'), ('actavatv', 'ActavaTV')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='viewing',
            unique_together=set([('date', 'domain', 'threshold', 'stream_type')]),
        ),
    ]
